---
- name: Download Linux git repositories
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ kalice_share_dir }}/{{ item.name }}"
  loop: "{{ kalice_linux_repositories }}"
  ignore_errors: true
  tags: linux

- name: Download Windows git repositories
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ kalice_windows_dir }}/{{ item.name }}"
  loop: "{{ kalice_windows_repositories }}"
  ignore_errors: true
  tags: windows
